FROM mhart/alpine-node:14 as builder
WORKDIR /app

COPY ./models ./models
COPY ./traffic-tester ./traffic-tester

RUN yarn --cwd ./traffic-tester install --frozen-lockfile
RUN yarn --cwd ./traffic-tester build

FROM mhart/alpine-node:14
WORKDIR /app

COPY --from=builder /app/traffic-tester/dist ./dist
COPY --from=builder /app/traffic-tester/node_modules ./node_modules
COPY --from=builder /app/traffic-tester/package.json .

EXPOSE 4000
CMD [ "yarn", "start:prod" ]
